export const products = [
  {
    id: 113,
    title: "Generic Motorcycle",
    description:
      "The Generic Motorcycle is a versatile and reliable bike suitable for various riding preferences. With a balanced design, it provides a comfortable and efficient riding experience.",
    category: "motorcycle",
    price: 3999.99,
    discountPercentage: 2.89,
    rating: 4.85,
    stock: 63,
    tags: ["motorcycles"],
    brand: "Generic Motors",
    sku: "8MOWO363",
    weight: 9,
    dimensions: {
      width: 14.87,
      height: 16.41,
      depth: 12.98,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Rodriguez",
        reviewerEmail: "mia.rodriguez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Owen Sullivan",
        reviewerEmail: "owen.sullivan@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Nicholas Edwards",
        reviewerEmail: "nicholas.edwards@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "3727788887261",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/1.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/2.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/3.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/thumbnail.png",
  },
  {
    id: 114,
    title: "Kawasaki Z800",
    description:
      "The Kawasaki Z800 is a powerful and agile sportbike known for its striking design and performance. It's equipped with advanced features, making it a favorite among motorcycle enthusiasts.",
    category: "motorcycle",
    price: 8999.99,
    discountPercentage: 15.07,
    rating: 4.06,
    stock: 88,
    tags: ["motorcycles", "sportbikes"],
    brand: "Kawasaki",
    sku: "9WBTI8EP",
    weight: 7,
    dimensions: {
      width: 28.34,
      height: 11.9,
      depth: 8.19,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Dylan Wells",
        reviewerEmail: "dylan.wells@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "0537669788973",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/1.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/2.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/3.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/thumbnail.png",
  },
  {
    id: 115,
    title: "MotoGP CI.H1",
    description:
      "The MotoGP CI.H1 is a high-performance motorcycle inspired by MotoGP racing technology. It offers cutting-edge features and precision engineering for an exhilarating riding experience.",
    category: "motorcycle",
    price: 14999.99,
    discountPercentage: 17,
    rating: 4.15,
    stock: 85,
    tags: ["motorcycles", "sportbikes"],
    brand: "MotoGP",
    sku: "0ENL5IX6",
    weight: 9,
    dimensions: {
      width: 27.4,
      height: 10.05,
      depth: 5.17,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Aaliyah Hanson",
        reviewerEmail: "aaliyah.hanson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jacob Cooper",
        reviewerEmail: "jacob.cooper@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Samantha Martinez",
        reviewerEmail: "samantha.martinez@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "0702250890221",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/1.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/2.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/3.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/thumbnail.png",
  },
  {
    id: 116,
    title: "Scooter Motorcycle",
    description:
      "The Scooter Motorcycle is a practical and fuel-efficient bike ideal for urban commuting. It features a step-through design and user-friendly controls for easy maneuverability.",
    category: "motorcycle",
    price: 2999.99,
    discountPercentage: 19.19,
    rating: 3.33,
    stock: 11,
    tags: ["motorcycles", "scooters"],
    brand: "ScootMaster",
    sku: "RGF3EX5E",
    weight: 2,
    dimensions: {
      width: 8.02,
      height: 10.2,
      depth: 17.22,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Ariana Ross",
        reviewerEmail: "ariana.ross@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Eleanor Collins",
        reviewerEmail: "eleanor.collins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Lily Lee",
        reviewerEmail: "lily.lee@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "5433184150501",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/1.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/2.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/3.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/thumbnail.png",
  },
  {
    id: 117,
    title: "Sportbike Motorcycle",
    description:
      "The Sportbike Motorcycle is designed for speed and agility, with a sleek and aerodynamic profile. It's suitable for riders looking for a dynamic and thrilling riding experience.",
    category: "motorcycle",
    price: 7499.99,
    discountPercentage: 18.07,
    rating: 2.97,
    stock: 12,
    tags: ["motorcycles", "sportbikes"],
    brand: "SpeedMaster",
    sku: "MW0SG302",
    weight: 9,
    dimensions: {
      width: 17.16,
      height: 15.02,
      depth: 15.03,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aurora Lawson",
        reviewerEmail: "aurora.lawson@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lily Lee",
        reviewerEmail: "lily.lee@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "0047068612003",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/1.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/2.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/3.png",
      "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/thumbnail.png",
  },
  {
    id: 118,
    title: "Attitude Super Leaves Hand Soap",
    description:
      "Attitude Super Leaves Hand Soap is a natural and nourishing hand soap enriched with the goodness of super leaves. It cleanses and moisturizes your hands, leaving them feeling fresh and soft.",
    category: "skin-care",
    price: 8.99,
    discountPercentage: 17.42,
    rating: 4.68,
    stock: 98,
    tags: ["personal care", "hand soap"],
    brand: "Attitude",
    sku: "E6U3C701",
    weight: 6,
    dimensions: {
      width: 9.98,
      height: 14.56,
      depth: 19.38,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Luke Cooper",
        reviewerEmail: "luke.cooper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mason Parker",
        reviewerEmail: "mason.parker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ella Adams",
        reviewerEmail: "ella.adams@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 32,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "4295199431696",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/1.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/2.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/thumbnail.png",
  },
  {
    id: 119,
    title: "Olay Ultra Moisture Shea Butter Body Wash",
    description:
      "Olay Ultra Moisture Shea Butter Body Wash is a luxurious body wash that hydrates and nourishes your skin with the moisturizing power of shea butter. Enjoy a rich lather and silky-smooth skin.",
    category: "skin-care",
    price: 12.99,
    discountPercentage: 16.95,
    rating: 4.81,
    stock: 43,
    tags: ["personal care", "body wash"],
    brand: "Olay",
    sku: "BZCSD4EX",
    weight: 8,
    dimensions: {
      width: 8.6,
      height: 28.86,
      depth: 22.75,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Miles Stevenson",
        reviewerEmail: "miles.stevenson@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Henry Hill",
        reviewerEmail: "henry.hill@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 23,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7184195298854",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/1.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/2.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/thumbnail.png",
  },
  {
    id: 120,
    title: "Vaseline Men Body and Face Lotion",
    description:
      "Vaseline Men Body and Face Lotion is a specially formulated lotion designed to provide long-lasting moisture to men's skin. It absorbs quickly and helps keep the skin hydrated and healthy.",
    category: "skin-care",
    price: 9.99,
    discountPercentage: 11.63,
    rating: 3.97,
    stock: 54,
    tags: ["personal care", "body lotion"],
    brand: "Vaseline",
    sku: "31IK2JUC",
    weight: 10,
    dimensions: {
      width: 28.39,
      height: 25.58,
      depth: 15.49,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Carter Rivera",
        reviewerEmail: "carter.rivera@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Jackson Morales",
        reviewerEmail: "jackson.morales@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Grace Green",
        reviewerEmail: "grace.green@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 48,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7128996084231",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/1.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/2.png",
      "https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/thumbnail.png",
  },
  {
    id: 121,
    title: "iPhone 5s",
    description:
      "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
    category: "smartphones",
    price: 199.99,
    discountPercentage: 11.85,
    rating: 3.92,
    stock: 65,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "AZ1L68SM",
    weight: 4,
    dimensions: {
      width: 8.49,
      height: 25.34,
      depth: 18.12,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Wyatt Perry",
        reviewerEmail: "wyatt.perry@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Olivia Anderson",
        reviewerEmail: "olivia.anderson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mateo Nguyen",
        reviewerEmail: "mateo.nguyen@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2903942810911",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/thumbnail.png",
  },
  {
    id: 122,
    title: "iPhone 6",
    description:
      "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 4.54,
    rating: 3.76,
    stock: 99,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "ZPXH3X9J",
    weight: 8,
    dimensions: {
      width: 16.21,
      height: 22.94,
      depth: 5.63,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Gavin Stanley",
        reviewerEmail: "gavin.stanley@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2517230562429",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/thumbnail.png",
  },
  {
    id: 123,
    title: "iPhone 13 Pro",
    description:
      "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
    category: "smartphones",
    price: 1099.99,
    discountPercentage: 18.3,
    rating: 3.42,
    stock: 26,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "YGQKHPGK",
    weight: 8,
    dimensions: {
      width: 22.39,
      height: 9.77,
      depth: 19.6,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ryan Graham",
        reviewerEmail: "ryan.graham@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2986724589988",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png",
  },
  {
    id: 124,
    title: "iPhone X",
    description:
      "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
    category: "smartphones",
    price: 899.99,
    discountPercentage: 14.19,
    rating: 4.96,
    stock: 99,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "9QN3UDUD",
    weight: 10,
    dimensions: {
      width: 27.86,
      height: 8.53,
      depth: 17.07,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "4331405454760",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png",
  },
  {
    id: 125,
    title: "Oppo A57",
    description:
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 12.17,
    rating: 3.1,
    stock: 76,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "J1NO9ULG",
    weight: 3,
    dimensions: {
      width: 29.52,
      height: 11.25,
      depth: 14.41,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nora Mills",
        reviewerEmail: "nora.mills@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1743445108634",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/thumbnail.png",
  },
  {
    id: 126,
    title: "Oppo F19 Pro Plus",
    description:
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
    category: "smartphones",
    price: 399.99,
    discountPercentage: 15.62,
    rating: 2.57,
    stock: 92,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "H2TTGWXB",
    weight: 2,
    dimensions: {
      width: 20.35,
      height: 16.4,
      depth: 13.31,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Harper Garcia",
        reviewerEmail: "harper.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7451360954140",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/thumbnail.png",
  },
  {
    id: 127,
    title: "Oppo K1",
    description:
      "The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.58,
    rating: 3.39,
    stock: 61,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "ELZ94HM3",
    weight: 2,
    dimensions: {
      width: 21.83,
      height: 27.83,
      depth: 27.47,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nathan Reed",
        reviewerEmail: "nathan.reed@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Madison Stewart",
        reviewerEmail: "madison.stewart@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7535531820285",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/3.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/thumbnail.png",
  },
];